//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.WCF_Blackbox {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacificCodeViewModel", Namespace="http://schemas.datacontract.org/2004/07/MoneyPacificBlackBox.DTO")]
    [System.SerializableAttribute()]
    public partial class PacificCodeViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActualAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InitialAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartCodeNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActualAmount {
            get {
                return this.ActualAmountField;
            }
            set {
                if ((this.ActualAmountField.Equals(value) != true)) {
                    this.ActualAmountField = value;
                    this.RaisePropertyChanged("ActualAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeNumber {
            get {
                return this.CodeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeNumberField, value) != true)) {
                    this.CodeNumberField = value;
                    this.RaisePropertyChanged("CodeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpireDate {
            get {
                return this.ExpireDateField;
            }
            set {
                if ((this.ExpireDateField.Equals(value) != true)) {
                    this.ExpireDateField = value;
                    this.RaisePropertyChanged("ExpireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InitialAmount {
            get {
                return this.InitialAmountField;
            }
            set {
                if ((this.InitialAmountField.Equals(value) != true)) {
                    this.InitialAmountField = value;
                    this.RaisePropertyChanged("InitialAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartCodeNumber {
            get {
                return this.PartCodeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PartCodeNumberField, value) != true)) {
                    this.PartCodeNumberField = value;
                    this.RaisePropertyChanged("PartCodeNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Blackbox.IBlackBoxService")]
    public interface IBlackBoxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/NewPacificCode", ReplyAction="http://tempuri.org/IBlackBoxService/NewPacificCodeResponse")]
        string NewPacificCode(int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/IsPossible", ReplyAction="http://tempuri.org/IBlackBoxService/IsPossibleResponse")]
        bool IsPossible(string codeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/IsExist", ReplyAction="http://tempuri.org/IBlackBoxService/IsExistResponse")]
        bool IsExist(string codeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/IsExistPart", ReplyAction="http://tempuri.org/IBlackBoxService/IsExistPartResponse")]
        bool IsExistPart(string partCodeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/GetPacificCodeViewModel", ReplyAction="http://tempuri.org/IBlackBoxService/GetPacificCodeViewModelResponse")]
        Merchant.WCF_Blackbox.PacificCodeViewModel GetPacificCodeViewModel(string partCodeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/GetArrayPacificCodeViewModel", ReplyAction="http://tempuri.org/IBlackBoxService/GetArrayPacificCodeViewModelResponse")]
        Merchant.WCF_Blackbox.PacificCodeViewModel[] GetArrayPacificCodeViewModel(string[] arrPartCodeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/ChangeCode", ReplyAction="http://tempuri.org/IBlackBoxService/ChangeCodeResponse")]
        string ChangeCode(string codeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/GetValue", ReplyAction="http://tempuri.org/IBlackBoxService/GetValueResponse")]
        int GetValue(string partCodeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/GetExpireDate", ReplyAction="http://tempuri.org/IBlackBoxService/GetExpireDateResponse")]
        System.DateTime GetExpireDate(string partCodeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/MakePayment", ReplyAction="http://tempuri.org/IBlackBoxService/MakePaymentResponse")]
        string MakePayment(string codeNumber, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/MakePaymentTo", ReplyAction="http://tempuri.org/IBlackBoxService/MakePaymentToResponse")]
        bool MakePaymentTo(string codeNumber, string partCodeNumber, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/Merge", ReplyAction="http://tempuri.org/IBlackBoxService/MergeResponse")]
        string Merge(string[] arrCodeNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlackBoxServiceChannel : Merchant.WCF_Blackbox.IBlackBoxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlackBoxServiceClient : System.ServiceModel.ClientBase<Merchant.WCF_Blackbox.IBlackBoxService>, Merchant.WCF_Blackbox.IBlackBoxService {
        
        public BlackBoxServiceClient() {
        }
        
        public BlackBoxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackBoxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackBoxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackBoxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string NewPacificCode(int amount) {
            return base.Channel.NewPacificCode(amount);
        }
        
        public bool IsPossible(string codeNumber) {
            return base.Channel.IsPossible(codeNumber);
        }
        
        public bool IsExist(string codeNumber) {
            return base.Channel.IsExist(codeNumber);
        }
        
        public bool IsExistPart(string partCodeNumber) {
            return base.Channel.IsExistPart(partCodeNumber);
        }
        
        public Merchant.WCF_Blackbox.PacificCodeViewModel GetPacificCodeViewModel(string partCodeNumber) {
            return base.Channel.GetPacificCodeViewModel(partCodeNumber);
        }
        
        public Merchant.WCF_Blackbox.PacificCodeViewModel[] GetArrayPacificCodeViewModel(string[] arrPartCodeNumber) {
            return base.Channel.GetArrayPacificCodeViewModel(arrPartCodeNumber);
        }
        
        public string ChangeCode(string codeNumber) {
            return base.Channel.ChangeCode(codeNumber);
        }
        
        public int GetValue(string partCodeNumber) {
            return base.Channel.GetValue(partCodeNumber);
        }
        
        public System.DateTime GetExpireDate(string partCodeNumber) {
            return base.Channel.GetExpireDate(partCodeNumber);
        }
        
        public string MakePayment(string codeNumber, int amount) {
            return base.Channel.MakePayment(codeNumber, amount);
        }
        
        public bool MakePaymentTo(string codeNumber, string partCodeNumber, int amount) {
            return base.Channel.MakePaymentTo(codeNumber, partCodeNumber, amount);
        }
        
        public string Merge(string[] arrCodeNumber) {
            return base.Channel.Merge(arrCodeNumber);
        }
    }
}
