//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyPacificService.WCF_Blackbox {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Blackbox.IBlackBoxService")]
    public interface IBlackBoxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/NewPacificCode", ReplyAction="http://tempuri.org/IBlackBoxService/NewPacificCodeResponse")]
        string NewPacificCode(int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/IsPossible", ReplyAction="http://tempuri.org/IBlackBoxService/IsPossibleResponse")]
        bool IsPossible(string codeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/ChangeCode", ReplyAction="http://tempuri.org/IBlackBoxService/ChangeCodeResponse")]
        string ChangeCode(int codeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/GetValue", ReplyAction="http://tempuri.org/IBlackBoxService/GetValueResponse")]
        int GetValue(string partCodeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/MakePayment", ReplyAction="http://tempuri.org/IBlackBoxService/MakePaymentResponse")]
        string MakePayment(string codeNumber, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/MakePaymentTo", ReplyAction="http://tempuri.org/IBlackBoxService/MakePaymentToResponse")]
        bool MakePaymentTo(string codeNumber, string partCodeNumber, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackBoxService/Merge", ReplyAction="http://tempuri.org/IBlackBoxService/MergeResponse")]
        string Merge(string[] arrCodeNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlackBoxServiceChannel : MoneyPacificService.WCF_Blackbox.IBlackBoxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlackBoxServiceClient : System.ServiceModel.ClientBase<MoneyPacificService.WCF_Blackbox.IBlackBoxService>, MoneyPacificService.WCF_Blackbox.IBlackBoxService {
        
        public BlackBoxServiceClient() {
        }
        
        public BlackBoxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackBoxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackBoxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackBoxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string NewPacificCode(int amount) {
            return base.Channel.NewPacificCode(amount);
        }
        
        public bool IsPossible(string codeNumber) {
            return base.Channel.IsPossible(codeNumber);
        }
        
        public string ChangeCode(int codeNumber) {
            return base.Channel.ChangeCode(codeNumber);
        }
        
        public int GetValue(string partCodeNumber) {
            return base.Channel.GetValue(partCodeNumber);
        }
        
        public string MakePayment(string codeNumber, int amount) {
            return base.Channel.MakePayment(codeNumber, amount);
        }
        
        public bool MakePaymentTo(string codeNumber, string partCodeNumber, int amount) {
            return base.Channel.MakePaymentTo(codeNumber, partCodeNumber, amount);
        }
        
        public string Merge(string[] arrCodeNumber) {
            return base.Channel.Merge(arrCodeNumber);
        }
    }
}
