//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorPacificCode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneratorPacificCode.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PacificCode&gt;  
        ///  &lt;parameter name=&quot;a&quot; index=&quot;1&quot; value=&quot;random&quot;/&gt;
        ///  &lt;parameter name=&quot;b&quot; index=&quot;2&quot; value=&quot;random&quot;/&gt;
        ///  &lt;parameter name=&quot;c&quot; index=&quot;3&quot; value=&quot;random&quot;/&gt;
        ///  &lt;parameter name=&quot;d&quot; index=&quot;4&quot; value=&quot;random&quot;/&gt;
        ///
        ///  &lt;parameter name=&quot;e&quot; index=&quot;5&quot; value=&quot;random&quot;/&gt;
        ///  &lt;parameter name=&quot;f&quot; index=&quot;6&quot; value=&quot;random&quot;/&gt;
        ///  &lt;parameter name=&quot;g&quot; index=&quot;7&quot; value=&quot;random&quot;/&gt;
        ///  &lt;parameter name=&quot;h&quot; index=&quot;8&quot; value=&quot;random&quot;/&gt;
        ///
        ///  &lt;parameter name=&quot;i&quot; index=&quot;9&quot; value=&quot;random&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PacificCodeRule {
            get {
                return ResourceManager.GetString("PacificCodeRule", resourceCulture);
            }
        }
    }
}
