//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyPacificService.DTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentModel", Namespace="http://schemas.datacontract.org/2004/07/MoneyPacificService.DTO")]
    public partial class PaymentModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMain")]
public interface IMain
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/SendMessage", ReplyAction="http://tempuri.org/IMain/SendMessageResponse")]
    string SendMessage(string smsContent);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMain/MakePayment", ReplyAction="http://tempuri.org/IMain/MakePaymentResponse")]
    MoneyPacificService.DTO.PaymentModel MakePayment(string[] LstCodeNumber, int Amount);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMainChannel : IMain, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MainClient : System.ServiceModel.ClientBase<IMain>, IMain
{
    
    public MainClient()
    {
    }
    
    public MainClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MainClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string SendMessage(string smsContent)
    {
        return base.Channel.SendMessage(smsContent);
    }
    
    public MoneyPacificService.DTO.PaymentModel MakePayment(string[] LstCodeNumber, int Amount)
    {
        return base.Channel.MakePayment(LstCodeNumber, Amount);
    }
}
