//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyPacificBlackBox.DTO
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PacificCodeViewModel", Namespace = "http://schemas.datacontract.org/2004/07/MoneyPacificBlackBox.DTO")]
    public partial class PacificCodeViewModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int ActualAmountField;

        private string CodeNumberField;

        private System.DateTime ExpireDateField;

        private int InitialAmountField;

        private string PartCodeNumberField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActualAmount
        {
            get
            {
                return this.ActualAmountField;
            }
            set
            {
                this.ActualAmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeNumber
        {
            get
            {
                return this.CodeNumberField;
            }
            set
            {
                this.CodeNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpireDate
        {
            get
            {
                return this.ExpireDateField;
            }
            set
            {
                this.ExpireDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InitialAmount
        {
            get
            {
                return this.InitialAmountField;
            }
            set
            {
                this.InitialAmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartCodeNumber
        {
            get
            {
                return this.PartCodeNumberField;
            }
            set
            {
                this.PartCodeNumberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IBlackBoxService")]
public interface IBlackBoxService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/NewPacificCode", ReplyAction = "http://tempuri.org/IBlackBoxService/NewPacificCodeResponse")]
    string NewPacificCode(int amount);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/IsPossible", ReplyAction = "http://tempuri.org/IBlackBoxService/IsPossibleResponse")]
    bool IsPossible(string codeNumber);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/IsExist", ReplyAction = "http://tempuri.org/IBlackBoxService/IsExistResponse")]
    bool IsExist(string codeNumber);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/GetPacificCodeViewModel", ReplyAction = "http://tempuri.org/IBlackBoxService/GetPacificCodeViewModelResponse")]
    MoneyPacificBlackBox.DTO.PacificCodeViewModel GetPacificCodeViewModel(string partCodeNumber);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/ChangeCode", ReplyAction = "http://tempuri.org/IBlackBoxService/ChangeCodeResponse")]
    string ChangeCode(int codeNumber);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/GetValue", ReplyAction = "http://tempuri.org/IBlackBoxService/GetValueResponse")]
    int GetValue(string partCodeNumber);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/GetExpireDate", ReplyAction = "http://tempuri.org/IBlackBoxService/GetExpireDateResponse")]
    System.DateTime GetExpireDate(string partCodeNumber);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/MakePayment", ReplyAction = "http://tempuri.org/IBlackBoxService/MakePaymentResponse")]
    string MakePayment(string codeNumber, int amount);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/MakePaymentTo", ReplyAction = "http://tempuri.org/IBlackBoxService/MakePaymentToResponse")]
    bool MakePaymentTo(string codeNumber, string partCodeNumber, int amount);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBlackBoxService/Merge", ReplyAction = "http://tempuri.org/IBlackBoxService/MergeResponse")]
    string Merge(string[] arrCodeNumber);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBlackBoxServiceChannel : IBlackBoxService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BlackBoxServiceClient : System.ServiceModel.ClientBase<IBlackBoxService>, IBlackBoxService
{

    public BlackBoxServiceClient()
    {
    }

    public BlackBoxServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public BlackBoxServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public BlackBoxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public BlackBoxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string NewPacificCode(int amount)
    {
        return base.Channel.NewPacificCode(amount);
    }

    public bool IsPossible(string codeNumber)
    {
        return base.Channel.IsPossible(codeNumber);
    }

    public bool IsExist(string codeNumber)
    {
        return base.Channel.IsExist(codeNumber);
    }

    public MoneyPacificBlackBox.DTO.PacificCodeViewModel GetPacificCodeViewModel(string partCodeNumber)
    {
        return base.Channel.GetPacificCodeViewModel(partCodeNumber);
    }

    public string ChangeCode(int codeNumber)
    {
        return base.Channel.ChangeCode(codeNumber);
    }

    public int GetValue(string partCodeNumber)
    {
        return base.Channel.GetValue(partCodeNumber);
    }

    public System.DateTime GetExpireDate(string partCodeNumber)
    {
        return base.Channel.GetExpireDate(partCodeNumber);
    }

    public string MakePayment(string codeNumber, int amount)
    {
        return base.Channel.MakePayment(codeNumber, amount);
    }

    public bool MakePaymentTo(string codeNumber, string partCodeNumber, int amount)
    {
        return base.Channel.MakePaymentTo(codeNumber, partCodeNumber, amount);
    }

    public string Merge(string[] arrCodeNumber)
    {
        return base.Channel.Merge(arrCodeNumber);
    }
}
